# ==============================================================================
# ProGuard / R8 Rules for Neon Music Player
# Includes Media3, Room, Hilt, WebView JavaScriptInterface, and Coroutines
# ==============================================================================

# ------------------------------------------------------------------------------
# General & Stack Trace Preservation
# ------------------------------------------------------------------------------
-keepattributes SourceFile,LineNumberTable,*Annotation*,InnerClasses,EnclosingMethod,Signature,Exceptions
-renamesourcefileattribute SourceFile
-dontnote **
-dontwarn javax.annotation.**
-dontwarn javax.inject.**

# ------------------------------------------------------------------------------
# AndroidX Media3 & MediaSession
# ------------------------------------------------------------------------------
# Prevent R8 from stripping Media3 renderers, extractors, decoders and session logic
-keep class androidx.media3.exoplayer.** { *; }
-keep interface androidx.media3.exoplayer.** { *; }
-keep class androidx.media3.session.** { *; }
-keep interface androidx.media3.session.** { *; }
-keep class androidx.media3.common.** { *; }
-keep interface androidx.media3.common.** { *; }
-keep class androidx.media3.datasource.** { *; }
-keep class androidx.media3.extractor.** { *; }

# Media3 utilizes reflection for dynamically loaded decoders and renderers
-keep class * extends androidx.media3.exoplayer.Renderer {
    public <init>(...);
}
-keep class * implements androidx.media3.extractor.Extractor {
    public <init>();
}
-keep class androidx.media3.exoplayer.audio.DefaultAudioSink { *; }
-keep class androidx.media3.session.MediaSessionService { *; }
-keep class com.example.service.MusicPlaybackService { *; }

# Suppress warnings for optional decoders/libraries that may not be linked
-dontwarn androidx.media3.**

# ------------------------------------------------------------------------------
# AndroidX Room Persistence
# ------------------------------------------------------------------------------
# Keep Room database definitions and generated _Impl classes
-keep class * extends androidx.room.RoomDatabase
-keep class * extends androidx.room.migration.Migration
-keep class androidx.room.RoomDatabase { *; }
-keep class androidx.sqlite.db.** { *; }

# Keep all Room entities, DAOs, and generated implementations
-keep @androidx.room.Entity class * { *; }
-keep @androidx.room.Dao interface * { *; }
-keep class * extends androidx.room.EntityInsertionAdapter { *; }
-keep class * extends androidx.room.EntityDeletionOrUpdateAdapter { *; }
-keep class * extends androidx.room.SharedSQLiteStatement { *; }
-keep class *_Impl {
    public <init>(...);
}

# Keep project-specific Room entities and DAOs
-keep class com.example.data.db.entity.** { *; }
-keep interface com.example.data.db.dao.** { *; }
-keep class com.example.data.db.AppMusicDatabase** { *; }
-keep class com.example.data.model.** { *; }

# Keep TypeConverters methods
-keepclassmembers class * {
    @androidx.room.TypeConverter <methods>;
}

-dontwarn androidx.room.paging.**

# ------------------------------------------------------------------------------
# Dagger & Google Hilt
# ------------------------------------------------------------------------------
# Keep Hilt annotations and entry point components
-keep,allowobfuscation,allowshrinking @interface dagger.hilt.**
-keep,allowobfuscation,allowshrinking @interface dagger.hilt.codegen.**

# Keep Hilt generated component classes and managers
-keep class * extends dagger.hilt.internal.GeneratedComponentManager { *; }
-keep class * extends dagger.hilt.internal.ComponentManager { *; }
-keep class *_HiltModules* { *; }
-keep class * extends androidx.lifecycle.ViewModel {
    public <init>(...);
}
-keep class * extends androidx.lifecycle.ViewModelProvider$Factory { *; }

# Keep classes annotated with Hilt entry points
-keep @dagger.hilt.android.AndroidEntryPoint class * { *; }
-keep @dagger.hilt.android.HiltAndroidApp class * { *; }
-keep @dagger.hilt.DefineComponent class * { *; }
-keep @dagger.hilt.EntryPoint class * { *; }

# Suppress harmless warnings from Dagger / Hilt generated bytecode
-dontwarn dagger.hilt.**
-dontwarn dagger.internal.**

# ------------------------------------------------------------------------------
# WebView & JavaScript Interface Bridge
# ------------------------------------------------------------------------------
# CRITICAL: Preserve @JavascriptInterface methods so JS can invoke native bridge
-keepattributes JavascriptInterface
-keepclassmembers class * {
    @android.webkit.JavascriptInterface <methods>;
}

# Explicitly retain the bridge package and all its public members
-keep class com.example.bridge.** {
    public *;
}

# ------------------------------------------------------------------------------
# Kotlin Coroutines & Flow
# ------------------------------------------------------------------------------
-keepnames class kotlinx.coroutines.internal.MainDispatcherFactory {}
-keepnames class kotlinx.coroutines.CoroutineExceptionHandler {}
-keepclassmembernames class kotlinx.coroutines.** {
    volatile <fields>;
}
-dontwarn kotlinx.coroutines.**

# ------------------------------------------------------------------------------
# JSON Parsing & Data Transfer
# ------------------------------------------------------------------------------
-keepclassmembers class org.json.** { *; }
